[file_default]
indent_width = 4
ansi_color = false

[file.rs]
compiler = { command=["rustc", "$FILE_PATH", "--error-format=json"], type="rustc", optimize_option=["-O"] }
lsp = ["rls"]
formatter = ["rustfmt"]
test_command = ["./$FILE_STEM"]

[file.cpp]
# Respect clang-format
indent_width = 2
compiler = { command=["clang", "$FILE_PATH", "-o", "$FILE_STEM"], type="gcc", optimize_option=["-O2"] }
lsp = ["clangd"]
formatter = ["clang-format"]
test_command = ["./$FILE_STEM"]

[file.rb]
indent_width = 2
